name: Publish on NPM

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - package.json

permissions:
    contents: write
    id-token: write

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4

            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                  node-version: lts/*
                  registry-url: "https://registry.npmjs.org"
                  package-manager-cache: false

            - name: Installing NPM deps
              run: pnpm install

            - name: Running tests
              run: pnpm run test

            - name: Build modules
              run: pnpm run build

            - name: Publishing on NPM
              id: publish
              uses: JS-DevTools/npm-publish@v4
              with:
                  token: ${{secrets.NPM_TOKEN}}
                  provenance: true

            - if: ${{ steps.publish.outputs.type }}
              run: |
                  pnpm pack

            - name: Release on GitHub
              if: ${{ steps.publish.outputs.type }}
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ steps.publish.outputs.version }}
                  draft: false
                  generate_release_notes: true
                  files: |
                      *.tgz
