name: Publish on NPM

on:
    workflow_dispatch:
    push:
        paths:
            - "package.json"

permissions:
    contents: read
    id-token: write

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: "https://registry.npmjs.org"

            - name: Installing NPM deps
              run: npm install

            - name: Running tests
              run: npm run test

            - name: Build modules
              run: npm run build

            - name: Publishing on NPM
              uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{secrets.NPM_TOKEN}}
                  provenance: true
